### ISSUE TITLE
Test documentation examples

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy#1382] opened 2022-09-02 13:01 UTC
Smithy code examples in the documentation are very useful and informative.

It'd be very nice if they could be automatically checked for correctness.

I'm probably spoiled by the Rust documentation tooling. In Rust, the documentation tooling has the concept of [documentation tests](https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html), where you can write a code example within documentation blocks that both appears in the rendered documentation and is compiled and ran when building it. You have the ability to also [hide portions of the example](https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html#hiding-portions-of-the-example) that are needed to make the test compile but that would distract a documentation reader, and to define whether the test should fail or not. Documentation tooling that builds atop this, like [mdBook](https://rust-lang.github.io/mdBook/format/mdbook.html), honor doctests and have even more features.

Now, I don't think this can be done natively in reStructuredText (they have the notion of ["doctest blocks"](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#doctest-blocks), but only for Python), but I think we could get a far way by leveraging [the `literalinclude` directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#doctest-blocks): we could place all the examples in separate Smithy files (whilst hiding the distracting boilerplate `:lines:`), and then run the Smithy tooling through all those files in CI to ensure they don't emit any warnings.

This is just a seed idea, more sophisticated things could be done with the code examples, but I hope I conveyed the value of having such a mechanism in place.

**Comment by mtdowling** [comment] 2022-09-04 16:43
I think this is a duplicate of https://github.com/awslabs/smithy/issues/298

**Closed by mtdowling** 2022-09-04 16:43 UTC
