### ISSUE TITLE
smith-openapi should honor @examples trait

### ISSUE THREAD

**Issue by jabalsad** [awslabs/smithy#1225] opened 2022-05-13 20:37 UTC
From what I can tell, the openapi source projection currently does not include any of the examples defined in the smithy specification.

**Comment by mtdowling** [comment] 2022-05-13 22:40
Yes it should. This is a duplicate of https://github.com/awslabs/smithy/issues/921 though so resolving in favor of that.

**Closed by mtdowling** 2022-05-13 22:40 UTC
